# Generated by Django 3.0.5 on 2020-05-12 22:53

import AppForNetwork.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FILE_EXEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/exel', validators=[AppForNetwork.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='NETWORKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('admin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RESULT_TEACHING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('information_teach', models.TextField()),
                ('result_teach', models.TextField()),
                ('id_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppForNetwork.NETWORKS')),
            ],
        ),
        migrations.CreateModel(
            name='PARAMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount_params', models.IntegerField()),
                ('amount_network', models.IntegerField()),
                ('amount_layers', models.IntegerField()),
                ('name_function', models.CharField(max_length=30)),
                ('accuracy', models.IntegerField()),
                ('max_time', models.CharField(max_length=30)),
                ('classs', models.CharField(max_length=30)),
                ('id_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppForNetwork.NETWORKS')),
            ],
        ),
        migrations.AddField(
            model_name='networks',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppForNetwork.Users'),
        ),
        migrations.CreateModel(
            name='DESCRIPTIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.TextField()),
                ('long_text', models.TextField()),
                ('id_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppForNetwork.NETWORKS')),
            ],
        ),
        migrations.CreateModel(
            name='DATASET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('id_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppForNetwork.NETWORKS')),
            ],
        ),
        migrations.CreateModel(
            name='COMMENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_param', models.IntegerField()),
                ('comment', models.TextField()),
                ('id_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppForNetwork.NETWORKS')),
            ],
        ),
    ]
