# Generated by Django 3.0.5 on 2020-05-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppForNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_exel',
            name='id_network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppForNetwork.NETWORKS'),
            preserve_default=False,
        ),
    ]
